-- DECLARE
--     CURSOR cur_funcao IS
--         SELECT 
--             COD,
--             COD_SIAPE,
--             NOME_FUNCAO
--         FROM BAR_FUNCAO;

--     v_sql VARCHAR2(1000);
-- BEGIN
--     FOR rec IN cur_funcao LOOP
--         v_sql := 'INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES ('
--                  || rec.COD || ', '
--                  || NVL(TO_CHAR(rec.COD_SIAPE), 'NULL') || ', '''
--                  || rec.NOME_FUNCAO || ''');';

--         DBMS_OUTPUT.PUT_LINE(v_sql);
--     END LOOP;
-- END;
-- /


CREATE TABLE BAR_FUNCAO (
    COD NUMBER PRIMARY KEY,
    COD_SIAPE VARCHAR2(20),
    NOME_FUNCAO VARCHAR2(255)
);
/

INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (22, 'FEX0116', 'FUNCÃO COMISSIONADA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (23, 'FEX0112', 'FUNCÃO COMISSIONADA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (24, 'FEX0109', 'FUNCÃO COMISSIONADA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (25, 'FEX0104', 'FUNCÃO COMISSIONADA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (26, 'FEX0108', 'FUNCÃO COMISSIONADA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (27, 'FEX0113', 'FUNCÃO COMISSIONADA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (28, 'FEX0105', 'FUNCÃO COMISSIONADA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (29, 'CCX0111', 'CARGO COMISSIONADO EXECUTIVO');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (42, 'CCX0117', 'CARGO COMISSIONADO EXECUTIVO');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (43, 'CCX0215', 'CARGO COMISSIONADO EXECUTIVO');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (44, 'FEX0107', 'FUNCÃO COMISSIONADA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (45, 'FEX0110', 'FUNCÃO COMISSIONADA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (46, 'FEX0106', 'FUNCÃO COMISSIONADA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (47, 'FEX0111', 'FUNCÃO COMISSIONADA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (30, 'CGE0004', 'CARGO COMISS. DE GERENCIA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (31, 'CCT0005', 'CARGO COMISSIONADO DE TECNICO');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (32, 'CCD0001', 'CARGO COMISSIONADO DE DIRECAO');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (33, 'CCD0002', 'CARGO COMISSIONADO DE DIRECAO');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (34, 'CGE0002', 'CARGO COMISS. DE GERENCIA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (35, 'CCT0004', 'CARGO COMISSIONADO DE TECNICO');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (36, 'CGE0001', 'CARGO COMISS. DE GERENCIA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (37, 'CAS0002', 'CARGO COMISSIONADO DE ASSISTENCIA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (38, 'CA 0002', 'CARGO COMISSIONADO DE ASSESSORIA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (39, 'CCT0003', 'CARGO COMISSIONADO DE TECNICO');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (40, 'CGE0003', 'CARGO COMISS. DE GERENCIA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (41, 'CCT0001', 'CARGO COMISSIONADO DE TECNICO');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (21, 'FEX0115', 'FUNCÃO COMISSIONADA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (81, 'FEX0209', 'FUNCÃO COMISSIONADA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (82, 'FEX0205', 'FUNCÃO COMISSIONADA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (83, 'CCX0115', 'CARGO COMISSIONADO EXECUTIVO');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (84, 'CCX0108', 'CARGO COMISSIONADO EXECUTIVO');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (85, 'FEX0206', 'FUNCÃO COMISSIONADA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (86, 'FEX0215', 'FUNCÃO COMISSIONADA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (87, 'FEX0211', 'FUNCÃO COMISSIONADA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (88, 'FEX0207', 'FUNCÃO COMISSIONADA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (89, 'FEX0208', 'FUNCÃO COMISSIONADA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (90, 'FEX0204', 'FUNCÃO COMISSIONADA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (91, 'CCX0104', 'CARGO COMISSIONADO EXECUTIVO');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (92, 'FEX0101', 'FUNCÃO COMISSIONADA EXECUTIVA');
INSERT INTO BAR_FUNCAO (COD, COD_SIAPE, NOME_FUNCAO) VALUES (61, 'CCX0118', 'CARGO COMISSIONADO EXECUTIVO');