-- DECLARE
--     CURSOR cur_cargo IS
--         SELECT 
--             COD,
--             NOME_CARGO
--         FROM BAR_CARGO;

--     v_sql VARCHAR2(1000);
-- BEGIN
--     FOR rec IN cur_cargo LOOP
--         v_sql := 'INSERT INTO BAR_CARGO (COD, NOME_CARGO) VALUES ('
--                  || rec.COD || ', '''
--                  || rec.NOME_CARGO || ''');';

--         DBMS_OUTPUT.PUT_LINE(v_sql);
--     END LOOP;
-- END;
-- /


CREATE TABLE BAR_CARGO (
    COD NUMBER PRIMARY KEY,
    NOME_CARGO VARCHAR2(255)
);
/

INSERT INTO BAR_CARGO (COD, NOME_CARGO) VALUES (441008, 'ESP EM REG DE SERV DE TRANSP AQUAVIARIOS');
INSERT INTO BAR_CARGO (COD, NOME_CARGO) VALUES (441001, 'ANALISTA ADMINISTRATIVO');
INSERT INTO BAR_CARGO (COD, NOME_CARGO) VALUES (441018, 'TECNICO ADMINISTRATIVO');
INSERT INTO BAR_CARGO (COD, NOME_CARGO) VALUES (441015, 'TEC E REG DE SERV DE TRANSP AQUAVIARIOS');
INSERT INTO BAR_CARGO (COD, NOME_CARGO) VALUES (446008, 'ENGENHEIRO');
INSERT INTO BAR_CARGO (COD, NOME_CARGO) VALUES (446001, 'ADMINISTRADOR');
INSERT INTO BAR_CARGO (COD, NOME_CARGO) VALUES (446002, 'ANALISTA DE SISTEMA');
INSERT INTO BAR_CARGO (COD, NOME_CARGO) VALUES (446062, 'PROGRAMADOR');
INSERT INTO BAR_CARGO (COD, NOME_CARGO) VALUES (446050, 'AGENTE ADMINISTRATIVO');
INSERT INTO BAR_CARGO (COD, NOME_CARGO) VALUES (-3, 'CEDIDO/REQUISITADO');
INSERT INTO BAR_CARGO (COD, NOME_CARGO) VALUES (-44, 'EXERC. 7  ART93 8112');
INSERT INTO BAR_CARGO (COD, NOME_CARGO) VALUES (-70, 'ESTAGIARIO SIGEPE');
INSERT INTO BAR_CARGO (COD, NOME_CARGO) VALUES (-18, 'EXERC DESCENT CARREI');
INSERT INTO BAR_CARGO (COD, NOME_CARGO) VALUES (-4, 'NOMEADO CARGO COMIS.');
INSERT INTO BAR_CARGO (COD, NOME_CARGO) VALUES (-14, 'REQ.DE OUTROS ORGAOS');
INSERT INTO BAR_CARGO (COD, NOME_CARGO) VALUES (-16, 'REQ. MILITAR F. ARM');