-- DECLARE
--     CURSOR cur_tipo_afastamento IS
--         SELECT 
--             COD,
--             DESCR_TIPO_AFASTAMENTO
--         FROM BAR_TIPO_AFASTAMENTO;

--     v_sql VARCHAR2(1000);
-- BEGIN
--     FOR rec IN cur_tipo_afastamento LOOP
--         v_sql := 'INSERT INTO BAR_TIPO_AFASTAMENTO (COD, DESCR_TIPO_AFASTAMENTO) VALUES ('
--                  || rec.COD || ', '''
--                  || rec.DESCR_TIPO_AFASTAMENTO || ''');';

--         DBMS_OUTPUT.PUT_LINE(v_sql);
--     END LOOP;
-- END;
-- /

CREATE TABLE BAR_TIPO_AFASTAMENTO (
    COD NUMBER PRIMARY KEY,
    DESCR_TIPO_AFASTAMENTO VARCHAR2(255)
);

INSERT INTO BAR_TIPO_AFASTAMENTO (COD, DESCR_TIPO_AFASTAMENTO) VALUES (1, 'Férias');
INSERT INTO BAR_TIPO_AFASTAMENTO (COD, DESCR_TIPO_AFASTAMENTO) VALUES (3, 'Ocorrência');
INSERT INTO BAR_TIPO_AFASTAMENTO (COD, DESCR_TIPO_AFASTAMENTO) VALUES (2, 'LPA - Licença Prêmio');
INSERT INTO BAR_TIPO_AFASTAMENTO (COD, DESCR_TIPO_AFASTAMENTO) VALUES (4, 'Reclusão');