-- DECLARE
--     CURSOR cur_tipo_ocorrencia IS
--         SELECT 
--             COD,
--             DESCR_TIPO_OCORRENCIA
--         FROM BAR_TIPO_OCORRENCIA;

--     v_sql VARCHAR2(1000);
-- BEGIN
--     FOR rec IN cur_tipo_ocorrencia LOOP
--         v_sql := 'INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES ('
--                  || rec.COD || ', '''
--                  || rec.DESCR_TIPO_OCORRENCIA || ''');';

--         DBMS_OUTPUT.PUT_LINE(v_sql);
--     END LOOP;
-- END;
-- /


CREATE TABLE BAR_TIPO_OCORRENCIA (
    COD NUMBER PRIMARY KEY,
    DESCR_TIPO_OCORRENCIA VARCHAR2(255)
);

INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (60, 'Falecimento Pessoa da  Familia - EST');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (86, 'Lic. Paternidade - EST');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (324, 'Lic. Paternidade Prorrogação - EST');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (270, 'LICENCA TRATAMENTO SAUDE INFERIOR 15 DIA');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (81, 'Lic. Capacitação - EST');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (396, 'LIC CAPAC - ART 25, INC I - DEC 9991/201');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (54, 'Doação de Sangue - EST');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (84, 'LIC. TRATAMENTO DE SAUDE - EST');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (55, 'Eleitoral Convocação Servidores - Lei 9.');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (90, 'Lic. por Motivo de Doença em Pessoa da F');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (49, 'Casamento / União Estável (Lic. Gala) -');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (47, 'Atraso ou Saída Antecipada - EST');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (52, 'Deslocam. Nova Sede Situação em Transito');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (33, 'Afas. Programa de Treinamento Com Ônus -');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (387, 'TRABALHO REMOTO COVID-19');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (79, 'Lic. Atividade Politica Com Remuneração');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (338, 'Lic. Ativ. Política C/Rem. (Desincompati');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (85, 'Lic. Tratar de Interesses Particulares -');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (404, 'Lic. Tratar de Interesses Particulares P');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (389, 'TELETRABALHO INTEGRAL - PROGRAMA DE GEST');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (277, 'Licença  Mot. Doença Pessoa Familia Infe');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (149, 'Lic. Maternidade -  RGPS');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (87, 'Lic. Acidente em Serviço - EST');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (397, 'LIC CAPAC - ART 25, INC II - DEC 9991/20');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (167, 'LIC. TRATAMENTO SAUDE  (+ DE 15 DIAS)  -');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (74, 'Lic. Gestante  ( Concedida Administrat.)');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (73, 'Lic. Gestante Prorrogação - EST');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (104, 'Afas. Part. Prog. Trein. (Congr) No e Fo');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (124, 'Falecimento Pessoa Familia - CLT');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (24, 'Afas. Missão Exterior Com Ônus - EST');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (40, 'Afas. Viagem/Serv Fora do País Com Ônus');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (414, 'AFAST REMUN COMPENSATORIA  S/PAGTO - EST');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (22, 'Afas. Juri e Outros Serviços - EST');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (66, 'Falta - EST');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (388, 'AFASTAMENTO COVID-19');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (93, 'Penalidade Suspensão Convertida em Multa');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (46, 'Ausência Alistamento Eleitoral - EST');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (261, 'Lic. Gestante (Concedida SIASS) - EST');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (19, 'Afas. Exer. Mand. Elet. Vereador C/Remun');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (14, 'Afas. Exer. Mand. Elet. Gov, Vice-Gov e');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (37, 'Afas. Servir a Outro Órgão (REQUISIÇÃO)');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (162, 'LIC. TRATAMENTO SAUDE - (ATE 15 DIAS) -');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (9, 'AFAS. CURSO FORMACAO OPCAO CARGO EFETIVO');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (94, 'Penalidade Suspensão - EST');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (29, 'Afas. Part.Prog.Trein.(Cong-Encont) Fora');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (25, 'Afas. Missão Exterior Com Ônus Limitado');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (30, 'Afas. Part.Prog.Trein. (Congr) Fora  Paí');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (42, 'Afas. Viagem/Serv País Com Ônus - EST');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (56, 'Eleitoral Suspensão Pagamento - EST');
INSERT INTO BAR_TIPO_OCORRENCIA (COD, DESCR_TIPO_OCORRENCIA) VALUES (12, 'Afas. Estudo Exterior C/Ônus Limitado -');