CREATE TABLE BAR_UORG (
    COD NUMBER PRIMARY KEY,
    NOME_UORG VARCHAR2(255),
    SIGLA_UORG VARCHAR2(50),
    COD_SIORG NUMBER,
    COD_UORG_SUPERIOR_AR NUMBER,
    COD_SERVIDOR_RESPONSAVEL_FK NUMBER,
    COD_GESTOR_RISCO_FK NUMBER,
    CREATED DATE,
    UPDATED TIMESTAMP,
    DELETED CHAR(1),
    COD_SIAPE NUMBER,
    NIVEL_CCE_FCE NUMBER
);
