-- Script Extras 01 --
-- Cleiton 12/11/2024 --
DECLARE
    V_EXISTE NUMBER;
BEGIN
    SELECT COUNT(1)
      INTO V_EXISTE 
      FROM CONFIGURACAO
     WHERE PARAMETRO = 'TIPO_AMBIENTE'
       AND VALOR IN ('HOMOLOGAÇÃO','HOMOLOGACAO','PRODUCAO','PRODUÇÃO');

    IF V_EXISTE > 0 THEN
        DELETE FROM CONFIGURACAO WHERE PARAMETRO = 'EMAIL_DESTINATARIO_TESTE';
    END IF;
END;
-- Script Extras 01 --