-- PRIMEIRO_NIVEL_MACROPROCESSO_BKP
alter table PLANO_ENTREGA add("PRIMEIRO_NIVEL_MACROPROCESSO_BKP" NUMBER);
update PLANO_ENTREGA set PRIMEIRO_NIVEL_MACROPROCESSO_BKP = PRIMEIRO_NIVEL_MACROPROCESSO;
update PLANO_ENTREGA set PRIMEIRO_NIVEL_MACROPROCESSO = null;
alter table PLANO_ENTREGA modify ("PRIMEIRO_NIVEL_MACROPROCESSO" NUMBER);
update PLANO_ENTREGA set PRIMEIRO_NIVEL_MACROPROCESSO = PRIMEIRO_NIVEL_MACROPROCESSO_BKP;
alter table PLANO_ENTREGA drop ("PRIMEIRO_NIVEL_MACROPROCESSO_BKP");


-- SEGUNDO_NIVEL_BKP
alter table PLANO_ENTREGA add("SEGUNDO_NIVEL_BKP" NUMBER);
update PLANO_ENTREGA set SEGUNDO_NIVEL_BKP = SEGUNDO_NIVEL;
update PLANO_ENTREGA set SEGUNDO_NIVEL = null;
alter table PLANO_ENTREGA modify ("SEGUNDO_NIVEL" NUMBER);
update PLANO_ENTREGA set SEGUNDO_NIVEL = SEGUNDO_NIVEL_BKP;
alter table PLANO_ENTREGA drop ("SEGUNDO_NIVEL_BKP");


-- TERCEIRO_NIVEL_BKP
alter table PLANO_ENTREGA add("TERCEIRO_NIVEL_BKP" NUMBER);
update PLANO_ENTREGA set TERCEIRO_NIVEL_BKP = TERCEIRO_NIVEL;
update PLANO_ENTREGA set TERCEIRO_NIVEL = null;
alter table PLANO_ENTREGA modify ("TERCEIRO_NIVEL" NUMBER);
update PLANO_ENTREGA set TERCEIRO_NIVEL = TERCEIRO_NIVEL_BKP;
alter table PLANO_ENTREGA drop ("TERCEIRO_NIVEL_BKP");


-- DEMANDANTE
alter table PLANO_ENTREGA add("DEMANDANTE_BKP" NUMBER);
update PLANO_ENTREGA set DEMANDANTE_BKP = DEMANDANTE;
alter table "WKSP_HEFESTO"."PLANO_ENTREGA" modify ("DEMANDANTE" VARCHAR2(120 CHAR) null);
update PLANO_ENTREGA set DEMANDANTE = NULL;
alter table PLANO_ENTREGA modify ("DEMANDANTE" NUMBER);
update PLANO_ENTREGA set DEMANDANTE = DEMANDANTE_BKP;
alter table PLANO_ENTREGA drop ("DEMANDANTE_BKP");
ALTER TABLE "PLANO_ENTREGA" ADD CONSTRAINT "PLANO_ENTREGA_FK_BAR_UORG_DEMANDANTE" FOREIGN KEY ("DEMANDANTE") REFERENCES "BAR_UORG" ("COD") ENABLE;
alter table "WKSP_HEFESTO"."PLANO_ENTREGA" modify ("DEMANDANTE" NUMBER not null);

-- DESTINATARIO
alter table PLANO_ENTREGA add("DESTINATARIO_BKP" NUMBER);
update PLANO_ENTREGA set DESTINATARIO_BKP = DESTINATARIO;
alter table "WKSP_HEFESTO"."PLANO_ENTREGA" modify ("DESTINATARIO" VARCHAR2(120 CHAR) null);
update PLANO_ENTREGA set DESTINATARIO = NULL;
alter table PLANO_ENTREGA modify ("DESTINATARIO" NUMBER);
update PLANO_ENTREGA set DESTINATARIO = DESTINATARIO_BKP;
alter table PLANO_ENTREGA drop ("DESTINATARIO_BKP");
ALTER TABLE "PLANO_ENTREGA" ADD CONSTRAINT "PLANO_ENTREGA_FK_BAR_UORG_DESTINATARIO" FOREIGN KEY ("DESTINATARIO") REFERENCES "BAR_UORG" ("COD") ENABLE;
alter table "WKSP_HEFESTO"."PLANO_ENTREGA" modify ("DESTINATARIO" NUMBER not null);

-- PROJETO
ALTER TABLE "PROJETO" ADD CONSTRAINT "PROJETO_FK_BAR_PESSOA_FISICA" FOREIGN KEY ("COD_GERENTE") REFERENCES "BAR_PESSOA_FISICA" ("COD") ENABLE;
