  CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_BAR_SERVIDOR" ("CODIGO_PESSOA", "CPF", "NOME_PESSOA_FISICA", "EMAIL_PESSOA_FISICA", "CODIGO_SERVIDOR", "NUM_SIAPE", "EMAIL_SERVIDOR", "CARGA_HORARIA_DISPONIVEL", "SIGLA_UORG", "NOME_UORG", "CODIGO_CARGO", "NOME_CARGO", "COD_SIAPE_FUNCAO", "CODIGO_FUNCAO", "NOME_FUNCAO", "COD_UORG", "COD_SERVIDOR_RESPONSAVEL_UORG", "COD_UORG_SUPERIOR") AS 
  SELECT PF.COD CODIGO_PESSOA
    ,  PF.NUM_CPF CPF
    ,  PF.NOME_PESSOA_FISICA
    ,  PF.EMAIL_PESSOA_FISICA
    ,  SE.COD CODIGO_SERVIDOR
    ,  SE.NUM_SIAPE
    ,  SE.EMAIL_SERVIDOR
    ,  SE.CARGA_HORARIA_DISPONIVEL
    ,  UO.SIGLA_UORG
    ,  UO.NOME_UORG
    ,  CA.COD CODIGO_CARGO
    ,  CA.NOME_CARGO
    ,  FU.COD CODIGO_FUNCAO
    ,  FU.COD_SIAPE COD_SIAPE_FUNCAO
    ,  FU.NOME_FUNCAO
    ,  SE.COD_UORG_EXERCICIO_FK COD_UORG
    ,  UO.COD_SERVIDOR_RESPONSAVEL_FK COD_SERVIDOR_RESPONSAVEL_UORG
    ,  UO.COD_UORG_SUPERIOR_AR COD_UORG_SUPERIOR
  FROM BAR_PESSOA_FISICA PF
    ,  BAR_SERVIDOR      SE
    ,  BAR_UORG          UO
    ,  BAR_FUNCAO        FU
    ,  BAR_CARGO         CA
 WHERE PF.COD                 = SE.COD_PESSOA_FISICA_FK
   AND NVL(SE.COD_UORG_EXERCICIO_FK,SE.COD_UORG_LOTACAO_FK) = UO.COD
   AND SE.COD_CARGO_FK        = CA.COD(+)
   AND SE.COD_FUNCAO_FK       = FU.COD(+);

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_BAR_SERVIDOR_AFASTAMENTO" ("CODIGO_PESSOA_FISICA", "CPF", "NOME_PESSOA_FISICA", "CODIGO_SERVIDOR", "DATA_INICIO_AFASTAMENTO", "DATA_FIM_AFASTAMENTO", "COD_TIPO_AFASTAMENTO", "DESCR_TIPO_AFASTAMENTO", "TEXTO_OBSERVACAO", "SIGLA_UORG_LOTACAO", "NOME_UORG_LOTACAO", "COD_TIPO_OCORRENCIA", "DESCR_TIPO_OCORRENCIA", "COD_OCORRENCIA", "TIPO_DEBITO", "MES_LIMITE_COMPENSACAO", "IND_DURACAO_HORAS") AS 
  SELECT PF.COD                       CODIGO_PESSOA_FISICA
    ,  PF.NUM_CPF                   CPF
    ,  PF.NOME_PESSOA_FISICA
    ,  SER.COD                      CODIGO_SERVIDOR
    ,  SEAF.DATA_INICIO_AFASTAMENTO
    ,  SEAF.DATA_FIM_AFASTAMENTO
    ,  TPAF.COD                     COD_TIPO_AFASTAMENTO
    ,  TPAF.DESCR_TIPO_AFASTAMENTO
    ,  ''                           TEXTO_OBSERVACAO
    ,  UO.SIGLA_UORG                SIGLA_UORG_LOTACAO
    ,  UO.NOME_UORG                 NOME_UORG_LOTACAO
    ,  TPOC.COD                     COD_TIPO_OCORRENCIA
    ,  TPOC.DESCR_TIPO_OCORRENCIA
    ,  0                            COD_OCORRENCIA
    ,  0                            TIPO_DEBITO
    ,  NULL                         MES_LIMITE_COMPENSACAO
    ,  8                            IND_DURACAO_HORAS
  FROM BAR_SERVIDOR             SER
    ,  BAR_PESSOA_FISICA        PF
    ,  BAR_UORG                 UO
    ,  BAR_SERVIDOR_AFASTAMENTO SEAF
    ,  BAR_TIPO_AFASTAMENTO     TPAF
    ,  BAR_TIPO_OCORRENCIA      TPOC
 WHERE SER.COD_PESSOA_FISICA_FK     = PF.COD
   AND SER.COD_UORG_LOTACAO_FK      = UO.COD
   AND SER.COD                      = SEAF.COD_SERVIDOR_FK
   AND SEAF.COD_TIPO_AFASTAMENTO_FK = TPAF.COD (+)
   AND SEAF.COD_OCORRENCIA_FK       = TPOC.COD (+)
UNION ALL
SELECT PF.COD                         CODIGO_PESSOA_FISICA
    ,  PF.NUM_CPF                     CPF
    ,  PF.NOME_PESSOA_FISICA 
    ,  SER.COD                            CODIGO_SERVIDOR
    ,  OC.DATA_INICIO                     DATA_INICIO_AFASTAMENTO
    ,  OC.DATA_FIM                        DATA_FIM_AFASTAMENTO
    ,  9999                               COD_TIPO_AFASTAMENTO
    ,  'Ocorrência cadastrada no sistema' DESCR_TIPO_AFASTAMENTO
    ,  OC.DESCRICAO                       TEXTO_OBSERVACAO
    ,  UO.SIGLA_UORG                      SIGLA_UORG_LOTACAO
    ,  UO.NOME_UORG                       NOME_UORG_LOTACAO
    ,  TP.COD                             COD_TIPO_OCORRENCIA
    ,  TP.DESCR_TIPO_OCORRENCIA
    ,  OC.COD                             COD_OCORRENCIA
    ,  OC.TIPO_DEBITO  
    ,  OC.MES_LIMITE_COMPENSACAO 
    ,  OC.IND_DURACAO_HORAS                  
  FROM OCORRENCIA          OC
    ,  BAR_SERVIDOR        SER
    ,  BAR_PESSOA_FISICA   PF
    ,  BAR_UORG            UO
    ,  BAR_TIPO_OCORRENCIA TP
 WHERE OC.COD_SERVIDOR_FK        = SER.COD
   AND SER.COD_PESSOA_FISICA_FK  = PF.COD
   AND SER.COD_UORG_LOTACAO_FK   = UO.COD
   AND OC.COD_TIPO_OCORRENCIA_FK = TP.COD;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_BAR_SERVIDOR_PESSOA_UORG" ("COD_SERVIDOR", "EMAIL_SERVIDOR", "COD_UORG_EXERCICIO", "CREATED", "UPDATED", "COD_PESSOA_FISICA", "NOME_PESSOA_FISICA", "COD_UORG", "NOME_UORG", "SIGLA_UORG") AS 
  SELECT S.COD                                        AS COD_SERVIDOR
       , S.EMAIL_SERVIDOR
       , S.COD_UORG_EXERCICIO_FK                      AS COD_UORG_EXERCICIO
       , S.CREATED                                    AS CREATED
       , S.UPDATED                                    AS UPDATED
       , PF.COD                                       AS COD_PESSOA_FISICA
       , PF.NOME_PESSOA_FISICA
       , U.COD                                        AS COD_UORG
       , U.NOME_UORG
       , U.SIGLA_UORG
    FROM BAR_PESSOA_FISICA PF
       , BAR_SERVIDOR      S
       , BAR_UORG          U
   WHERE PF.COD                                               = S.COD_PESSOA_FISICA_FK
     AND NVL(S.COD_UORG_EXERCICIO_FK,S.COD_UORG_LOTACAO_FK)   = U.COD;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_PLANO_ENTREGA" ("COD_PLANO_ENTREGA", "DESCRICAO_ENTREGA", "DESCRICAO_PLANO", "IND_ATIVO") AS 
  SELECT PE.COD_PLANO_ENTREGA 
    ,  CASE
        WHEN PE.CATEGORIA = 1 THEN PE.DESCRICAO_ENTREGA
        WHEN PE.CATEGORIA = 2 THEN (SELECT DESCR_PROJETO_TAREFA
                                      FROM PROJETO_TAREFA
                                     WHERE COD_PROJETO_TAREFA = PE.SELECIONE_ENTREGA)
       END AS DESCRICAO_ENTREGA
    ,  PL.DESCRICAO_PLANO
    ,  PE.IND_ATIVO
  FROM PLANO_ENTREGA PE
    ,  PLANO PL
 WHERE PE.COD_PLANO = PL.COD_PLANO(+);

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_PLANO_TRABALHO_HORA_COMPENSACAO" ("COD_SERVIDOR", "TOTAL_HORAS", "DATA_DEVOLVER") AS 
  SELECT PT.COD_SERVIDOR
    ,  sum(EX.IND_ESFORCO) AS TOTAL_HORAS
    ,  ADD_MONTHS(PT.DATA_FIM + 50, 1) AS  DATA_DEVOLVER
  FROM PLANO_TRABALHO_ATIVIDADE PA
    ,  VW_PLANO_ENTREGA PE
    ,  BAR_UORG             U
    ,  PLANO_TRABALHO PT
    ,  PLANO_TRABALHO_ATIVIDADE_EXECUCAO EX
 WHERE PA.COD_PLANO_ENTREGA  = PE.COD_PLANO_ENTREGA(+)
   AND PA.COD_UORG           = U.COD
   AND PA.IND_SITUACAO       = 'F'
   AND PT.COD_PLANO_TRABALHO = PA.COD_PLANO_TRABALHO
   AND EX.COD_PLANO_TRABALHO_ATIVIDADE = PA.COD_ATIVIDADE
   AND PA.AVALIACAO_COMPENSACAO = 1
 --  AND PA.AVALIACAO_RESULTADO = 5
group by PT.COD_SERVIDOR, PT.DATA_FIM;